[package]
description = "Bindings to LLVM's C API"
documentation = "http://rustdoc.taricorp.net/llvm-sys/llvm_sys/"
repository = "https://bitbucket.org/tari/llvm-sys.rs"
readme = "README.md"
license = "MIT"
keywords = ["bindings", "llvm"]

name = "llvm-sys"
version = "0.4.0"
authors = [
  "Peter Marheine <peter@taricorp.net>",
  "Scott Olson <scott@solson.me>",
]
build = "build.rs"

[dependencies]
bitflags = "0.7"
libc = "0.2"

[build-dependencies]
gcc = "0.3"
regex = "0.1.77"
semver = "0.4"
